
set(INCLUDE_INSTALL_DIR ${CMAKE_INSTALL_INCLUDEDIR})
set(LIB_INSTALL_DIR ${CMAKE_INSTALL_LIBDIR})
set(BIN_INSTALL_DIR ${CMAKE_INSTALL_BINDIR})
set(SYSCONFIG_INSTALL_DIR ${CMAKE_INSTALL_SYSCONFDIR})
set(OMNI_CMAKE_INSTALL_DIR ${CMAKE_INSTALL_DATAROOTDIR}/cmake/${PROJECT_NAME}/)






include(CMakePackageConfigHelpers)

configure_package_config_file(cmake/OmniOrbConfig.cmake.in ${PROJECT_BINARY_DIR}/OmniOrbConfig.cmake
        INSTALL_DESTINATION ${OMNI_CMAKE_INSTALL_DIR}
        PATH_VARS INCLUDE_INSTALL_DIR SYSCONFIG_INSTALL_DIR)

write_basic_package_version_file(${PROJECT_BINARY_DIR}/OmniOrbConfigVersion.cmake
        VERSION ${PROJECT_VERSION}
        COMPATIBILITY SameMajorVersion)

install(FILES ${CMAKE_CURRENT_BINARY_DIR}/OmniOrbConfig.cmake ${CMAKE_CURRENT_BINARY_DIR}/OmniOrbConfigVersion.cmake
        DESTINATION ${OMNI_CMAKE_INSTALL_DIR})


install(EXPORT ${PROJECT_NAME}Targets
        NAMESPACE "${PROJECT_NAME}::"
        DESTINATION ${OMNI_CMAKE_INSTALL_DIR}
        )